spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://serverIP:serverPort/service?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: username
    password: password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto:
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: 'COVID19-TASK-'

telegram:
  token: token
  sendMessageUrl: https://api.telegram.org/bottoken/sendMessage
  chatId: charId

government:
  api-key: private-api-key
  api-url: 'http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19SidoInfStateJson'

logging:
  file:
    name: government-corona-api-daemon.log
    max-size: 100MB